#!/bin/bash

set -e

GHC_VERSION="7.10.2"  
ARCHITECTURE="x86_64"  
# for 32 bit ARCHITECTURE="i386"      
PLATFORM="unknown-linux"  
GHC_DIST_FILENAME="ghc-$GHC_VERSION-$ARCHITECTURE-$PLATFORM-deb7.tar.bz2"

CABAL_VERSION="1.22.4.0"
CABAL_DIST_FILENAME="Cabal-$CABAL_VERSION.tar.gz"

CABAL_INSTALL_VERSION="1.22.6.0"
CABAL_INSTALL_DIST_FILENAME="cabal-install-$CABAL_INSTALL_VERSION.tar.gz"
